default_config:
  - config_name: openai-gpt4
configs:
  - config_name: openai-gpt4
    config:
      - provider: openai
        model: gpt-4
providers:
  - provider: openai
    env:
      api_key: YOUR_OPENAI_API_KEY
      base_url: https://api.openai.com/v1
      models:
        - model: gpt-4
        - model: gpt-3.5-turbo