name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      PLATFORM: win32
      ARCH: x64
      PACKAGE_NAME: qwen-code-router-win32-x64
      ARTIFACT_EXT: zip
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test

      - name: Build project
        run: pnpm build

      - name: Package as executable
        run: |
          pnpm install pkg
          pnpm pack:win

      - name: Create release directory
        run: mkdir -p release

      - name: Copy built files
        shell: bash
        run: |
          cp -r dist release/
          cp qcr.exe release/ || echo "qcr.exe not found, skipping"
          cp package.json release/
          cp README.md release/ || echo "README.md not found, skipping"
          cp README.zh-CN.md release/ || echo "README.zh-CN.md not found, skipping"
          cp LICENSE release/ || echo "LICENSE not found, skipping"
          cp config.example.yaml release/
          cp config.example.json release/
          cp INSTALL.md release/ || echo "INSTALL.md not found, skipping"
          cp INSTALL.zh-CN.md release/ || echo "INSTALL.zh-CN.md not found, skipping"
          cp CROSS_PLATFORM_SUMMARY.md release/ || echo "CROSS_PLATFORM_SUMMARY.md not found, skipping"
          cp CROSS_PLATFORM_SUMMARY.zh-CN.md release/ || echo "CROSS_PLATFORM_SUMMARY.zh-CN.md not found, skipping"
          cp RELEASE_NOTES.md release/ || echo "RELEASE_NOTES.md not found, skipping"
          cp RELEASE_NOTES.zh-CN.md release/ || echo "RELEASE_NOTES.zh-CN.md not found, skipping"

      - name: Copy platform-specific scripts (Windows)
        shell: bash
        run: |
          # Print current directory and list files for debugging
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "Bin directory contents:"
          ls -la bin/ || echo "Bin directory not found"
          
          mkdir -p release/bin
          
          # Try to copy qcr.bat
          if [ -f "bin/qcr.bat" ]; then
            echo "Found bin/qcr.bat, copying..."
            cp bin/qcr.bat release/bin/
          elif [ -f "./bin/qcr.bat" ]; then
            echo "Found ./bin/qcr.bat, copying..."
            cp ./bin/qcr.bat release/bin/
          else
            echo "Warning: bin/qcr.bat not found, creating minimal file"
            echo "@echo off" > release/bin/qcr.bat
            echo "node \"%~dp0/../dist/cli.js\" %*" >> release/bin/qcr.bat
          fi
          
          # Try to copy qcr.ps1
          if [ -f "bin/qcr.ps1" ]; then
            echo "Found bin/qcr.ps1, copying..."
            cp bin/qcr.ps1 release/bin/
          elif [ -f "./bin/qcr.ps1" ]; then
            echo "Found ./bin/qcr.ps1, copying..."
            cp ./bin/qcr.ps1 release/bin/
          else
            echo "Warning: bin/qcr.ps1 not found, creating minimal file"
            echo 'node "$PSScriptRoot/../dist/cli.js" $args' > release/bin/qcr.ps1
          fi
          
          # Try to copy install.bat
          if [ -f "install.bat" ]; then
            echo "Found install.bat, copying..."
            cp install.bat release/
          elif [ -f "./install.bat" ]; then
            echo "Found ./install.bat, copying..."
            cp ./install.bat release/
          else
            echo "Warning: install.bat not found, skipping"
          fi

      - name: Create platform-specific package
        shell: bash
        run: |
          cd release
          # Create platform-specific package.json
          node -e "
            const pkg = require('./package.json');
            pkg.name = '${{ env.PACKAGE_NAME }}';
            pkg.os = ['${{ env.PLATFORM }}'];
            pkg.cpu = ['${{ env.ARCH }}'];
            require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));
          "

      - name: Create single executable archive
        shell: powershell
        run: |
          # Create archive with just the executable file
          $version = "${{ github.ref_name }}".TrimStart("refs/tags/v")
          if ("${{ github.event_name }}" -eq "workflow_dispatch") {
            $version = "${{ github.event.inputs.version }}".TrimStart("v")
          }
          
          # Create a temporary directory with just the executable
          mkdir qcr-temp
          if (Test-Path "qcr.exe") {
            Copy-Item "qcr.exe" "qcr-temp\"
          } else {
            Copy-Item "release\qcr.exe" "qcr-temp\"
          }
          
          # Create the archive with just the executable
          Compress-Archive -Path "qcr-temp\*" -DestinationPath "qwen-code-router-$version-${{ env.PLATFORM }}-${{ env.ARCH }}-executable.${{ env.ARTIFACT_EXT }}"

      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PACKAGE_NAME }}-executable
          path: "*-executable.${{ env.ARTIFACT_EXT }}"

      - name: Create full archive
        shell: powershell
        run: |
          $version = "${{ github.ref_name }}".TrimStart("refs/tags/v")
          if ("${{ github.event_name }}" -eq "workflow_dispatch") {
            $version = "${{ github.event.inputs.version }}".TrimStart("v")
          }
          Compress-Archive -Path release/* -DestinationPath "qwen-code-router-$version-${{ env.PLATFORM }}-${{ env.ARCH }}.${{ env.ARTIFACT_EXT }}"

      - name: Upload full artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: "*.${{ env.ARTIFACT_EXT }}"

  build-linux:
    runs-on: ubuntu-latest
    env:
      PLATFORM: linux
      ARCH: x64
      PACKAGE_NAME: qwen-code-router-linux-x64
      ARTIFACT_EXT: tar.gz
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test

      - name: Build project
        run: pnpm build

      - name: Package as executable
        run: |
          pnpm install pkg
          pnpm pack:linux

      - name: Create release directory
        run: mkdir -p release

      - name: Copy built files
        run: |
          cp -r dist release/
          cp qcr release/ || echo "qcr executable not found, skipping"
          cp package.json release/
          cp README.md release/ || echo "README.md not found, skipping"
          cp README.zh-CN.md release/ || echo "README.zh-CN.md not found, skipping"
          cp LICENSE release/ || echo "LICENSE not found, skipping"
          cp config.example.yaml release/
          cp config.example.json release/
          cp INSTALL.md release/ || echo "INSTALL.md not found, skipping"
          cp INSTALL.zh-CN.md release/ || echo "INSTALL.zh-CN.md not found, skipping"
          cp CROSS_PLATFORM_SUMMARY.md release/ || echo "CROSS_PLATFORM_SUMMARY.md not found, skipping"
          cp CROSS_PLATFORM_SUMMARY.zh-CN.md release/ || echo "CROSS_PLATFORM_SUMMARY.zh-CN.md not found, skipping"
          cp RELEASE_NOTES.md release/ || echo "RELEASE_NOTES.md not found, skipping"
          cp RELEASE_NOTES.zh-CN.md release/ || echo "RELEASE_NOTES.zh-CN.md not found, skipping"

      - name: Copy platform-specific scripts (Unix)
        run: |
          mkdir -p release/bin
          cp bin/qcr release/bin/
          chmod +x release/bin/qcr
          cp install.sh release/ || echo "install.sh not found, skipping"
          chmod +x release/install.sh || echo "install.sh not found, skipping"

      - name: Create platform-specific package
        run: |
          cd release
          # Create platform-specific package.json
          node -e "
            const pkg = require('./package.json');
            pkg.name = '${{ env.PACKAGE_NAME }}';
            pkg.os = ['${{ env.PLATFORM }}'];
            pkg.cpu = ['${{ env.ARCH }}'];
            require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));
          "

      - name: Create single executable archive
        run: |
          # Create archive with just the executable file
          version="${{ github.ref_name }}"
          version="${version#refs/tags/v}"
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            version="${{ github.event.inputs.version }}"
            version="${version#v}"
          fi
          
          # Create a temporary directory with just the executable
          mkdir -p qcr-temp
          if [ -f "qcr" ]; then
            cp qcr qcr-temp/
          else
            cp release/qcr qcr-temp/
          fi
          
          # Make executable
          chmod +x qcr-temp/qcr
          
          # Create the archive with just the executable
          tar -czf "qwen-code-router-$version-${{ env.PLATFORM }}-${{ env.ARCH }}-executable.${{ env.ARTIFACT_EXT }}" -C qcr-temp .

      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PACKAGE_NAME }}-executable
          path: "*-executable.${{ env.ARTIFACT_EXT }}"

      - name: Create full archive
        run: |
          version="${{ github.ref_name }}"
          version="${version#refs/tags/v}"
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            version="${{ github.event.inputs.version }}"
            version="${version#v}"
          fi
          tar -czf "qwen-code-router-$version-${{ env.PLATFORM }}-${{ env.ARCH }}.${{ env.ARTIFACT_EXT }}" -C release .

      - name: Upload full artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: "*.${{ env.ARTIFACT_EXT }}"

  build-macos:
    runs-on: macos-latest
    env:
      PLATFORM: darwin
      ARCH: x64
      PACKAGE_NAME: qwen-code-router-darwin-x64
      ARTIFACT_EXT: tar.gz
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test

      - name: Build project
        run: pnpm build

      - name: Package as executable
        run: |
          pnpm install pkg
          pnpm pack:macos

      - name: Create release directory
        run: mkdir -p release

      - name: Copy built files
        run: |
          cp -r dist release/
          cp qcr release/ || echo "qcr executable not found, skipping"
          cp package.json release/
          cp README.md release/ || echo "README.md not found, skipping"
          cp README.zh-CN.md release/ || echo "README.zh-CN.md not found, skipping"
          cp LICENSE release/ || echo "LICENSE not found, skipping"
          cp config.example.yaml release/
          cp config.example.json release/
          cp INSTALL.md release/ || echo "INSTALL.md not found, skipping"
          cp INSTALL.zh-CN.md release/ || echo "INSTALL.zh-CN.md not found, skipping"
          cp CROSS_PLATFORM_SUMMARY.md release/ || echo "CROSS_PLATFORM_SUMMARY.md not found, skipping"
          cp CROSS_PLATFORM_SUMMARY.zh-CN.md release/ || echo "CROSS_PLATFORM_SUMMARY.zh-CN.md not found, skipping"
          cp RELEASE_NOTES.md release/ || echo "RELEASE_NOTES.md not found, skipping"
          cp RELEASE_NOTES.zh-CN.md release/ || echo "RELEASE_NOTES.zh-CN.md not found, skipping"

      - name: Copy platform-specific scripts (Unix)
        run: |
          mkdir -p release/bin
          cp bin/qcr release/bin/
          chmod +x release/bin/qcr
          cp install.sh release/ || echo "install.sh not found, skipping"
          chmod +x release/install.sh || echo "install.sh not found, skipping"

      - name: Create platform-specific package
        run: |
          cd release
          # Create platform-specific package.json
          node -e "
            const pkg = require('./package.json');
            pkg.name = '${{ env.PACKAGE_NAME }}';
            pkg.os = ['${{ env.PLATFORM }}'];
            pkg.cpu = ['${{ env.ARCH }}'];
            require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));
          "

      - name: Create single executable archive
        run: |
          # Create archive with just the executable file
          version="${{ github.ref_name }}"
          version="${version#refs/tags/v}"
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            version="${{ github.event.inputs.version }}"
            version="${version#v}"
          fi
          
          # Create a temporary directory with just the executable
          mkdir -p qcr-temp
          if [ -f "qcr" ]; then
            cp qcr qcr-temp/
          else
            cp release/qcr qcr-temp/
          fi
          
          # Make executable
          chmod +x qcr-temp/qcr
          
          # Create the archive with just the executable
          tar -czf "qwen-code-router-$version-${{ env.PLATFORM }}-${{ env.ARCH }}-executable.${{ env.ARTIFACT_EXT }}" -C qcr-temp .

      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PACKAGE_NAME }}-executable
          path: "*-executable.${{ env.ARTIFACT_EXT }}"

      - name: Create full archive
        run: |
          version="${{ github.ref_name }}"
          version="${version#refs/tags/v}"
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            version="${{ github.event.inputs.version }}"
            version="${version#v}"
          fi
          tar -czf "qwen-code-router-$version-${{ env.PLATFORM }}-${{ env.ARCH }}.${{ env.ARTIFACT_EXT }}" -C release .

      - name: Upload full artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: "*.${{ env.ARTIFACT_EXT }}"

  create-release:
    needs: [build-windows, build-linux, build-macos]
    runs-on: ubuntu-latest
    if: always() && (startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch')
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare release assets
        run: |
          mkdir -p release-assets
          find artifacts -name "*.zip" -o -name "*.tar.gz" -o -name "qcr*" -o -name "*-executable.*" | xargs -I {} cp {} release-assets/
          ls -la release-assets/

      - name: Get version
        id: get_version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            ref="${{ github.ref }}"
            version="${ref#refs/tags/}"
            echo "version=$version" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          name: Qwen Code Router ${{ steps.get_version.outputs.version }}
          body: |
            ## Qwen Code Router ${{ steps.get_version.outputs.version }}
            
            A command-line tool to manage and switch API configurations for different large model service providers when using Qwen Code.
            
            ### Features
            - ✅ Cross-platform support (Windows, Linux, macOS)
            - ✅ Multiple provider support (OpenAI, Azure, Anthropic, Google)
            - ✅ Easy configuration management
            - ✅ Quick provider/model switching
            - ✅ Configuration validation
            
            ### Downloads
            Choose the appropriate package for your platform:
            
            - **Windows**: `qwen-code-router-*-win32-x64.zip`
            - **Linux**: `qwen-code-router-*-linux-x64.tar.gz`
            - **macOS**: `qwen-code-router-*-darwin-x64.tar.gz`
            
            ### Installation
            1. Download the appropriate package for your platform
            2. Extract the archive
            3. Run the installation script (`install.bat` for Windows, `install.sh` for Unix)
            4. Or follow the manual installation instructions in `INSTALL.md`
            
            ### Quick Start
            ```bash
            # Copy example configuration
            cp config.example.yaml config.yaml
            
            # Edit configuration with your API keys
            # Then use the tool
            qcr list config
            qcr use openai-gpt4
            qcr run
            ```
            
            For detailed installation and usage instructions, see the included `INSTALL.md` file.
          draft: false
          prerelease: false
          files: |
            release-assets/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
